name: image_presenter
description: Digital signage application with web control
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.0
  
  # Web server
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  
  # Utilities
  path: ^1.9.0
  mime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true